### ISSUE TITLE
Cannot see autocomplete

### ISSUE THREAD

**Issue by MaelitoP** [pwnwriter/pwnvim#12]
Hello @pwnwriter,

I'm playing with your repo to discover `nvim`. But I don't understand why I cannot see any autocomplete for anything. Here is an example in rust.

I tried to follow keys defined in [lua/core/mappings.lua](https://github.com/pwnwriter/pwnvim/blob/main/lua/core/mappings.lua#L100) and in [lua/plugins/cmp.lua](https://github.com/pwnwriter/pwnvim/blob/ec9c1823459cdbaedbb4c021050fae9048a04771/lua/plugins/cmp.lua#L56), but it does nothing.
When I start typing `use rand::` nothing appears. It's the same in `INSERT` and `NORMAL` mode and with the `CTRL+SPACE` bind either.

Do you have any idea of what I'm doing wrong ?

![image](https://github.com/pwnwriter/pwnvim/assets/7220756/56b73de6-f22d-4cd1-8362-b75d3f983980)

Thank you for your help

**Comment by pwnwriter** [comment]
Hey, thanks for the issue 

Auto completion fairly works on my machine. 

A few things to notice and try debugging,

- [`/lua/plugins/servers.lua`](https://github.com/pwnwriter/pwnvim/blob/main/lua/plugins/servers.lua) has some configuration for a list of lsp severs I use. For rust, it uses `rustup` to invoke the `rust-analyzer` . 
- Check if rustup is installed or not if not install and then install rust-analyzer using rustup itself.
`rustup component add rust-analyzer`  I'm using stable rust . You should be able to change between nightly beta or stable from the servers.lua file.

**Comment by MaelitoP** [comment]
Hello !

Thank you so much for your help, it works better when `rust-analyser` is installed \o/
